definitions:
  controllers.Options:
    properties:
      emission:
        type: string
      text:
        type: string
    type: object
  controllers.PersonInf:
    properties:
      message:
        type: string
      score:
        type: string
      userId:
        type: integer
    type: object
  controllers.QuesInf:
    properties:
      key:
        type: string
      options:
        $ref: '#/definitions/controllers.Options'
      question:
        type: string
    type: object
  controllers.QuestionSub:
    properties:
      score:
        type: integer
      sub_key:
        type: string
    type: object
  controllers.Response:
    properties:
      data:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  controllers.ScoreInfo:
    properties:
      question_key:
        items:
          $ref: '#/definitions/controllers.QuestionSub'
        type: array
      question_name:
        type: string
    type: object
  controllers.UserLogin:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  controllers.UserRegister:
    properties:
      company_name:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      user_name:
        type: string
      user_type:
        type: string
    type: object
host: https://karbonizgi.leaflove.com.tr
info:
  contact: {}
  title: KARBONİZGİ
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: Chat Kısmı
      parameters:
      - description: Kullanıcının user id bilgisini ve ilk başta score bilgisini girmelisin.Score
          bilgisi /score endpointinde data kısmında dönüyor.Eğer kullanıcı konuşmayı
          devam ettirirse message kısmında kullanıcının mesajını gönderebilirsin.
        in: body
        name: PersonInf
        required: true
        schema:
          $ref: '#/definitions/controllers.PersonInf'
      produces:
      - application/json
      responses:
        "200":
          description: Message kısmını kullanıcıya gösterebilirsin.Eğer kullanıcı
            karbonayak izi dışında sorular sorarsa chat cevap vermez karbon ayak izine
            yönlendirir.2 kere gereksiz soru sorulursa data kısmında 'false' döner
            ve burada chat konuşmasını bitir sonra message kısmını kullanıcıya gösterebilirsin.
          schema:
            $ref: '#/definitions/controllers.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controllers.Response'
      summary: User chat Kısmı
      tags:
      - chat
  /company_questions:
    get:
      consumes:
      - application/json
      description: Şirket test kısmı
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.QuesInf'
      tags:
      - Test
  /login:
    post:
      consumes:
      - application/json
      description: Giriş kısmı
      parameters:
      - description: User login details
        in: body
        name: UserLogin
        required: true
        schema:
          $ref: '#/definitions/controllers.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: User login successfully
          schema:
            $ref: '#/definitions/controllers.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controllers.Response'
      summary: User Login
      tags:
      - User
  /logout:
    post:
      consumes:
      - application/json
      description: Çıkış kısmı
      produces:
      - application/json
      responses:
        "200":
          description: User Logout successfully
          schema:
            $ref: '#/definitions/controllers.Response'
      security:
      - BearerAuth: []
      summary: User Logout
      tags:
      - User
  /person_questions:
    get:
      consumes:
      - application/json
      description: Bireysel test kısmı
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.QuesInf'
      tags:
      - Test
  /register:
    post:
      consumes:
      - application/json
      description: Kayıt kısmı
      parameters:
      - description: user_type kısmına kullanıcı kişi ise 'person' şirket ise 'company'
          girmelisin. Kullanıcı bireysel ise company_name girmene gerek yok.
        in: body
        name: UserRegister
        required: true
        schema:
          $ref: '#/definitions/controllers.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/controllers.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controllers.Response'
      summary: User Registration
      tags:
      - User
  /score:
    post:
      consumes:
      - application/json
      description: Karbon Ayak İzi Hesaplanması
      parameters:
      - description: /company-questions ve /person-questions endpointlerinde belli
          bir key value değerine göre soruları döndüm. Bu değerleri kullanarak question_name
          ve question_key değerlerini ekleyebilirsin.
        in: body
        name: ScoreInfo
        required: true
        schema:
          $ref: '#/definitions/controllers.ScoreInfo'
      produces:
      - application/json
      responses:
        "200":
          description: data kısmında kullanıcının karbon ayak izi değeri döner.Chat
            kısmında bu kısmı kullanacaksın.
          schema:
            $ref: '#/definitions/controllers.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controllers.Response'
      summary: User Puan Kısmı
      tags:
      - Score
swagger: "2.0"
